name: GraphQL-DGS
on: push
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@main

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: maven build, clean
        run: |
          mvn clean package -DskipTests

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          az config set extension.use_dynamic_install=yes_without_prompt
      - run: |
          az spring app create --name graphql-dgs-netflix --instance-count 1 --assign-endpoint true --memory 2Gi --runtime-version Java_17 --jvm-options='-Xms2048m -Xmx2048m'

      - name: deploy to production with artifact
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ secrets.SUBSCRIPTION_ID }}
          action: deploy
          service-name: ${{ secrets.SERVICE_NAME }}
          app-name: graphql-dgs-netflix
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/target/*.jar
          runtime-version: Java_17